#include "lossless/lossless_mp3_hybrid.hpp"
#include "lossless/lossless_mp3_hybrid_detail.hpp"
#include <algorithm>
#include <array>
#include <atomic>
#include <cmath>
#include <cstdlib>
#include <iostream>
#include <limits>
#include <random>
#include <stdexcept>
#include <vector>
namespace {
constexpr double pi = 3.14159265358979323846;
void require(bool ok, const char* why) { if (!ok) { std::cerr << why << '\n'; std::exit(1); } }
void requireSame(const agplayer::lossless::MdctFrameEvidence& a,
                 const agplayer::lossless::MdctFrameEvidence& b, const char* why) {
    require(a.coherentPeakDb==b.coherentPeakDb && a.meanPeakZ==b.meanPeakZ
        && a.phaseConcentration==b.phaseConcentration && a.activeBlocks==b.activeBlocks
        && a.alignedBlocks==b.alignedBlocks,why);
}
auto scan(const std::vector<double>& x, std::size_t chunk, bool antiphase = false) {
    agplayer::lossless::Mp3HybridProbe p(44100, antiphase ? 2 : 1, x.size());
    std::atomic_bool cancel{false};
    for (std::size_t i = 0; i < x.size(); i += chunk) {
        const auto count = std::min(chunk, x.size() - i);
        if (!antiphase) p.consume(x.data() + i, count, cancel);
        else {
            std::vector<double> s(count * 2);
            for (std::size_t j = 0; j < count; ++j) { s[2*j] = x[i+j]; s[2*j+1] = -x[i+j]; }
            p.consume(s.data(), count, cancel);
        }
    }
    require(p.result().activeBlocks==0,"capture must not perform expensive analysis");
    p.refine(cancel);const auto first=p.result();p.refine(cancel);const auto second=p.result();
    require(first.coherentPeakDb==second.coherentPeakDb && first.activeBlocks==second.activeBlocks,"refine must be idempotent");
    return first;
}
}
int main() {
    using namespace agplayer::lossless;
    using namespace agplayer::lossless::mp3_hybrid_detail;
    // Independent center-frequency tones, not generated by the analysis bank.
    for (std::size_t b = 0; b < 32; ++b) {
        std::vector<double> x(1024);
        for (std::size_t n = 0; n < x.size(); ++n) x[n] = std::cos(pi/64*(2*b+1)*n);
        std::array<double,32> power{};
        for (std::size_t t = 511; t < x.size(); t += 7) {
            std::array<double,32> s{}; analysisSubbands(x.data()+t,s);
            for (std::size_t k = 0; k < 32; ++k) power[k] += s[k]*s[k];
        }
        require(static_cast<std::size_t>(std::max_element(power.begin(),power.end())-power.begin())==b,"subband center frequency mapped incorrectly");
    }
    LongMdct fft;
    std::mt19937 random(7319); std::uniform_real_distribution<double> uniform(-.3,.3);
    std::vector<double> signal(360), reconstructed(360,0.0);
    for (auto& v:signal) v=uniform(random);
    for (std::size_t start=0;start+36<=signal.size();start+=18) {
        std::array<double,18> coefficients{};fft.transform(signal.data()+start,coefficients.data());
        for (std::size_t k=0;k<18;++k) {
            double reference=0;
            for (std::size_t n=0;n<36;++n) reference+=signal[start+n]*std::sin(pi/36*(n+.5))*std::cos(pi/18*(n+.5+9)*(k+.5));
            require(std::abs(reference-coefficients[k])<1e-11,"36 FFT MDCT differs from independent cosine");
            for (std::size_t n=0;n<36;++n) reconstructed[start+n]+=(2.0/18)*coefficients[k]*std::sin(pi/36*(n+.5))*std::cos(pi/18*(n+.5+9)*(k+.5));
        }
    }
    for(std::size_t n=36;n+36<signal.size();++n)require(std::abs(signal[n]-reconstructed[n])<1e-11,"long MDCT overlap-add failed");
    std::array<double,576> bands{};for(auto& v:bands)v=uniform(random);const auto original=bands;
    aliasReduction(bands.data());
    constexpr std::array<double,8> ci{{-.6,-.535,-.33,-.185,-.095,-.041,-.0142,-.0037}};
    for(std::size_t b=1;b<32;++b)for(std::size_t k=0;k<8;++k){
        const auto up=b*18-1-k,down=b*18+k;const double cs=1/std::sqrt(1+ci[k]*ci[k]),ca=ci[k]*cs;
        const double u=bands[up],d=bands[down];bands[up]=u*cs-d*ca;bands[down]=u*ca+d*cs;
    }
    for(std::size_t i=0;i<bands.size();++i)require(std::abs(bands[i]-original[i])<1e-12,"alias inverse failed");
    // Independent scalar formula checks: every value keeps its original floor,
    // and a non-multiple-of-four tail is included without reading past the end.
    const std::array<double,13> magnitudes{{0.0,-0.0,std::numeric_limits<double>::denorm_min(),
        1e-10,std::nextafter(1e-10,0.0),std::nextafter(1e-10,1.0),-.125,.37,
        1e-308,-1e-9,2.75,-13.0,.001}};
    for(std::size_t count=0;count<=magnitudes.size();++count){
        double expected=12.5,actual=12.5;
        for(std::size_t i=0;i<count;++i)expected+=20*std::log10(std::max(1e-10,std::abs(magnitudes[i])));
        require(accumulateLogEnergy(magnitudes.data(),count,actual),"finite log magnitudes were rejected");
        require(std::abs(actual-expected)<=1e-10,"batched log energy differs from the scalar formula");
    }
    const std::array<double,8> overflowProducts{{1e300,1e300,1e300,1e300,1e308,1e308,1e-10,1e-10}};
    double overflowExpected=0,overflowActual=0;
    for(const auto v:overflowProducts)overflowExpected+=20*std::log10(std::max(1e-10,std::abs(v)));
    require(accumulateLogEnergy(overflowProducts.data(),overflowProducts.size(),overflowActual)
        && overflowActual==overflowExpected,"finite coefficients with overflowing products need the scalar fallback");
    for(const auto invalid:{std::numeric_limits<double>::infinity(),std::numeric_limits<double>::quiet_NaN()}){
        for(const std::size_t position:{0U,3U,4U}){
            std::array<double,5> nonfinite{{1,1,1,1,1}};nonfinite[position]=invalid;double energy=0;
            require(!accumulateLogEnergy(nonfinite.data(),nonfinite.size(),energy),"nonfinite log coefficient was accepted");
        }
    }
    std::vector<double> noise(36000);for(auto& v:noise)v=uniform(random);
    const auto whole=scan(noise,noise.size()),chunked=scan(noise,127),stereo=scan(noise,991,true);
    require(whole.activeBlocks==4,"four disjoint blocks were not measured");
    require(whole.coherentPeakDb==chunked.coherentPeakDb && whole.meanPeakZ==chunked.meanPeakZ && whole.alignedBlocks==chunked.alignedBlocks,"chunk boundaries changed analysis");
    require(whole.coherentPeakDb==stereo.coherentPeakDb && whole.meanPeakZ==stereo.meanPeakZ,"antiphase channels changed analysis");
    require(!(whole.coherentPeakDb>=2 && whole.meanPeakZ>=5 && whole.alignedBlocks>=3),"native noise incorrectly gave codec evidence");
    // The quieter channel must retain its own complete evidence. A known-codec
    // file regression separately checks that an energetic native channel cannot
    // hide lossy history in the other channel. This checks exact sample routing.
    std::vector<double> quiet(noise.size());for(auto& v:quiet)v=uniform(random)*.03;
    const auto quietReference=scan(quiet,quiet.size());
    const auto stereoScan=[&](std::size_t chunk,bool swapped,bool silentOther,int linkedPhase){
        Mp3HybridProbe p(44100,2,noise.size());std::atomic_bool stop{false};
        for(std::size_t i=0;i<noise.size();i+=chunk){
            const auto count=std::min(chunk,noise.size()-i);std::vector<double> block(count*2);
            for(std::size_t j=0;j<count;++j){
                block[j*2+(swapped?1:0)]=noise[i+j];
                block[j*2+(swapped?0:1)]=silentOther?0:linkedPhase!=0?linkedPhase*noise[i+j]:quiet[i+j];
            }
            p.consume(block.data(),count,stop);
        }
        p.refine(stop);const auto primary=p.result();
        require(p.alternateResult().activeBlocks==0,"primary refinement eagerly measured the alternate channel");
        stop=true;p.refineAlternate(stop);
        require(p.alternateResult().activeBlocks==0,"pre-cancelled alternate refinement must not start");
        stop=false;p.refineAlternate(stop);const auto alternate=p.alternateResult();
        p.refineAlternate(stop);requireSame(alternate,p.alternateResult(),"alternate refinement must be idempotent");
        requireSame(primary,p.result(),"alternate refinement changed primary evidence");
        return std::array<MdctFrameEvidence,2>{{primary,alternate}};
    };
    const auto dual=stereoScan(noise.size(),false,false,0);
    requireSame(dual[0],whole,"quiet alternate channel changed primary analysis");
    requireSame(dual[1],quietReference,"alternate analysis did not independently measure the quieter channel");
    const auto dualChunked=stereoScan(127,false,false,0),dualSwapped=stereoScan(991,true,false,0);
    requireSame(dual[1],dualChunked[1],"chunk boundaries changed alternate evidence");
    requireSame(dual[1],dualSwapped[1],"swapping stereo channels changed alternate evidence");
    require(stereoScan(991,false,true,0)[1].activeBlocks==0,"silent alternate channel must stay inactive");
    requireSame(stereoScan(991,false,false,-1)[1],whole,"antiphase alternate was mixed or cancelled");
    requireSame(stereoScan(991,false,false,1)[1],whole,"same-phase alternate was not preserved");
    Mp3HybridProbe monoOnly(44100,1,noise.size());std::atomic_bool alternateCancel{false};
    monoOnly.consume(noise.data(),noise.size(),alternateCancel);monoOnly.refineAlternate(alternateCancel);
    require(monoOnly.alternateResult().activeBlocks==0,"mono input invented an alternate channel");
    monoOnly.refine(alternateCancel);requireSame(monoOnly.result(),whole,"alternate call changed mono primary analysis");
    // A completed alternate attempt also freezes capture, even if it ran first.
    std::vector<double> pair(noise.size()*2);
    for(std::size_t i=0;i<noise.size();++i){pair[2*i]=noise[i];pair[2*i+1]=quiet[i];}
    Mp3HybridProbe alternateFirst(44100,2,noise.size());
    alternateFirst.consume(pair.data(),noise.size(),alternateCancel);alternateFirst.refineAlternate(alternateCancel);
    alternateFirst.consume(pair.data(),noise.size(),alternateCancel);alternateFirst.refine(alternateCancel);
    requireSame(alternateFirst.result(),whole,"alternate-first refinement changed primary capture");
    requireSame(alternateFirst.alternateResult(),quietReference,"alternate-first refinement changed alternate capture");
    std::atomic_bool cancelBeforeRefine{false};Mp3HybridProbe lazy(44100,1,noise.size());
    lazy.consume(noise.data(),noise.size(),cancelBeforeRefine);cancelBeforeRefine=true;lazy.refine(cancelBeforeRefine);
    require(lazy.result().activeBlocks==0,"pre-cancelled refine must not start");
    cancelBeforeRefine=false;lazy.refine(cancelBeforeRefine);
    require(lazy.result().coherentPeakDb==whole.coherentPeakDb,"pre-cancelled refine consumed its attempt");
    lazy.consume(noise.data(),noise.size(),cancelBeforeRefine);lazy.refine(cancelBeforeRefine);
    require(lazy.result().activeBlocks==4,"completed refinement must ignore additional capture");
    Mp3HybridProbe huge(44100,1,std::numeric_limits<std::uint64_t>::max());
    bool overflow=false;
    try { huge.consume(noise.data(),std::numeric_limits<std::size_t>::max(),cancelBeforeRefine); }
    catch(const std::overflow_error&){overflow=true;}
    require(overflow,"invalid input count must fail before pointer arithmetic");
    std::fill(noise.begin(),noise.end(),0);require(scan(noise,noise.size()).activeBlocks==0,"silence must be inactive");
    std::fill(noise.begin(),noise.end(),std::numeric_limits<double>::quiet_NaN());require(scan(noise,noise.size()).activeBlocks==0,"nonfinite input must be inactive");
    std::atomic_bool cancel{true};Mp3HybridProbe cancelled(44100,1,36000);cancelled.consume(noise.data(),noise.size(),cancel);require(cancelled.result().activeBlocks==0,"cancelled probe produced evidence");
    Mp3HybridProbe invalid(96000,1,36000);cancel=false;invalid.consume(noise.data(),noise.size(),cancel);require(invalid.result().activeBlocks==0,"unsupported rate produced evidence");
    Mp3HybridProbe shortFile(44100,1,100);shortFile.consume(noise.data(),100,cancel);require(shortFile.result().activeBlocks==0,"short file produced evidence");
    std::cout << "MP3 hybrid numerical and streaming tests passed\n";
}
