include_guard(GLOBAL)

function(agplayer_validate_macos_target)
    if(NOT CMAKE_SYSTEM_NAME STREQUAL "Darwin")
        message(FATAL_ERROR "AgPlayer's Apple target is macOS, not iOS or another Apple platform.")
    endif()
    if(NOT CMAKE_OSX_DEPLOYMENT_TARGET VERSION_EQUAL "13.0")
        message(FATAL_ERROR "AgPlayer macOS builds require CMAKE_OSX_DEPLOYMENT_TARGET=13.0.")
    endif()
    set(architectures ${CMAKE_OSX_ARCHITECTURES})
    list(REMOVE_DUPLICATES architectures)
    list(SORT architectures)
    if(NOT "${architectures}" STREQUAL "arm64;x86_64")
        message(FATAL_ERROR "AgPlayer macOS builds must be Universal: CMAKE_OSX_ARCHITECTURES=x86_64\;arm64.")
    endif()
endfunction()
