if(NOT DEFINED SOURCE_DIR)
  get_filename_component(SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
endif()
file(READ "${SOURCE_DIR}/qt/src/file_association_controller.cpp" runtime)
file(READ "${SOURCE_DIR}/installer/AgPlayer.iss" installer)
string(REGEX MATCH "kProgId\\[\\] = \"([^\"]+)\"" ignored "${runtime}")
set(prog_id "${CMAKE_MATCH_1}")
if(NOT prog_id OR NOT installer MATCHES "Classes\\\\${prog_id}\"")
  message(FATAL_ERROR "Installer and runtime must register the same ProgID")
endif()
foreach(required IN ITEMS "CurUninstallStepChanged" "RegGetSubkeyNames"
    "AgPlayer.Audio" "AgPlayerAudioFile" "OpenWithProgids")
  if(NOT installer MATCHES "${required}")
    message(FATAL_ERROR "Uninstall must remove only both AgPlayer-owned associations: ${required}")
  endif()
endforeach()
if(installer MATCHES "RegDeleteKeyIncludingSubkeys\\([^\n]*OpenWithProgids")
  message(FATAL_ERROR "Shared OpenWithProgids keys must never be deleted")
endif()
