cmake_minimum_required(VERSION 3.28)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
if(DEFINED CASE)
    include("${ROOT}/cmake/MacOS.cmake")
    set(CMAKE_SYSTEM_NAME Darwin)
    set(CMAKE_OSX_DEPLOYMENT_TARGET 13.0)
    set(CMAKE_OSX_ARCHITECTURES "x86_64;arm64")
    if(CASE STREQUAL "thin")
        set(CMAKE_OSX_ARCHITECTURES arm64)
    elseif(CASE STREQUAL "higher-minimum")
        set(CMAKE_OSX_DEPLOYMENT_TARGET 13.3)
    elseif(CASE STREQUAL "ios")
        set(CMAKE_SYSTEM_NAME iOS)
    elseif(CASE STREQUAL "reversed")
        set(CMAKE_OSX_ARCHITECTURES "arm64;x86_64")
    endif()
    agplayer_validate_macos_target()
    return()
endif()

foreach(case valid reversed thin higher-minimum ios)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DCASE=${case}" -P "${CMAKE_CURRENT_LIST_FILE}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(case STREQUAL "valid" OR case STREQUAL "reversed")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Valid universal target rejected (${case}): ${output}${error}")
        endif()
    elseif(result EQUAL 0)
        message(FATAL_ERROR "Invalid macOS target was accepted: ${case}")
    endif()
endforeach()
message(STATUS "macOS target contract: 5 cases passed")
