cmake_minimum_required(VERSION 3.28)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
file(READ "${ROOT}/CMakeLists.txt" config)
string(FIND "${config}" "set(AGPLAYER_DEFAULT_UPDATE_MANIFEST_URL" begin)
string(FIND "${config}" "if(AGPLAYER_UPDATE_MANIFEST_URL AND NOT" end)
math(EXPR length "${end} - ${begin}")
string(SUBSTRING "${config}" ${begin} ${length} update_config)
foreach(APPLE TRUE FALSE)
  foreach(case default legacy custom disabled)
    unset(AGPLAYER_UPDATE_MANIFEST_URL CACHE)
    unset(AGPLAYER_UPDATE_MANIFEST_URL)
    set(expected "https://download.agplayer.com/updates/latest.json")
    if(case STREQUAL legacy)
      set(AGPLAYER_UPDATE_MANIFEST_URL "https://download.agplayer.com/updates/macos/latest.json" CACHE STRING "" FORCE)
    elseif(case STREQUAL custom)
      set(expected "https://example.invalid/custom.json")
      set(AGPLAYER_UPDATE_MANIFEST_URL "${expected}" CACHE STRING "" FORCE)
    elseif(case STREQUAL disabled)
      set(expected "")
      set(AGPLAYER_UPDATE_MANIFEST_URL "" CACHE STRING "" FORCE)
    endif()
    cmake_language(EVAL CODE "${update_config}")
    if(NOT AGPLAYER_UPDATE_MANIFEST_URL STREQUAL expected)
      message(FATAL_ERROR "Update endpoint contract failed: APPLE=${APPLE}, case=${case}")
    endif()
  endforeach()
endforeach()
message(STATUS "Update endpoint contract: 8 cases passed")
